from typing import Any

class MysqlServer:
    def __init__(self, *args: Any, session_factory: Any = ..., **kwargs: Any) -> None: ...
    async def serve_forever(self) -> None: ...

class Session:
    middlewares: list[Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def dialect(self) -> Any: ...
