from collections.abc import Iterable
from typing import Any

class Column:
    def __init__(self, **kwargs: Any) -> None: ...

class InfoSchema:
    def __init__(self, tables: Any) -> None: ...

def dict_depth(value: Any) -> int: ...
def info_schema_tables(columns: Iterable[Column]) -> Any: ...
